# Generated by Django 2.0.3 on 2018-05-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
